name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_call:
    inputs:
      python-version:
        description: 'Python version(s) to test against as a comma-separated string.'
        required: false
        type: string
        default: '3.12'
      requirements:
        description: 'Path to a requirements.txt file to install before running tests. Leave empty (default) to install from pyproject.toml test dependencies.'
        required: false
        type: string
        default: ''

env:
  PYTHON_VERSION: ${{ inputs.python-version || '3.12' }} # override via python-version input or matrix in caller workflow

jobs:
  prepare-matrix:
    name: Prepare matrix
    runs-on: ubuntu-latest
    outputs:
      python-versions: ${{ steps.set-matrix.outputs.python-versions }}
      python-version-count: ${{ steps.set-matrix.outputs.python-version-count }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Action | Prepare matrix
        id: set-matrix
        uses: ./.github/actions/prepare-matrix
        with:
          python-version: ${{ env.PYTHON_VERSION }}

  test-matrix:
    name: Run matrix tests
    needs: [prepare-matrix]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ${{ fromJSON(needs.prepare-matrix.outputs.python-versions) }}

    steps:
      - uses: actions/checkout@v6
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}

      # --- Install dependencies ------------------------------------------------
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install pytest pytest-cov pytest-mock pytest-emoji
          if [ -n "$REQUIREMENTS" ]; then
            pip install -r $REQUIREMENTS
          else
            pip install ".[test]" || true
          fi

      # -------------------------------------------------------------------------
      - name: Run tests
        run: pytest -v --cov=src --cov-report=xml --cov-report=html --cov-report=term-missing || [ "$?" -eq 5 ]

      - name: Upload coverage report as artifact
        uses: actions/upload-artifact@v7
        with:
          name: 'coverage-report-${{ matrix.python-version }}'
          path: ./htmlcov
